function PTRRWASDOData = import_RWASDODEMO_file(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PTRRWASDODATA = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  PTRRWASDODATA = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  PTRRWASDOData = importfile("/Volumes/shlab/Projects/PTR/data/clean/RWA_SDO/PTR_RWA_SDO_Data .csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Jul-2022 15:50:01

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 49, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["SUBJID", "RWA_1", "RWA_2", "RWA_3", "RWA_4", "RWA_5", "RWA_6", "RWA_7", "RWA_8", "RWA_9", "RWA_10", "RWA_11", "RWA_12", "RWA_13", "RWA_14", "RWA_15", "RWA_16", "RWA_17", "RWA_18", "RWA_19", "RWA_20", "RWA_21", "RWA_22", "SDO_1", "SDO_2", "SDO_3", "SDO_4", "SDO_5", "SDO_6", "SDO_7", "SDO_8", "SDO_9", "SDO_10", "SDO_11", "SDO_12", "SDO_13", "SDO_14", "SDO_15", "SDO_16", "PA_LiberalCons_Scale", "PolParty0R1D2N", "IfPA0R1D", "Age", "Ethnicity0N1Y", "Race0W1B2A3L", "Gender0M1F", "GenderIdentity0M1F2O", "RWA_Score", "SDO_Score"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
PTRRWASDOData = readtable(filename, opts);

end