function PTRPOSTQ1 = import_postq_file(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PTRPOSTQ1 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  PTRPOSTQ1 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  PTRPOSTQ1 = importfile("/Volumes/shlab/Projects/PTR/data/clean/POST_Q/PTR_POSTQ.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Jul-2022 15:32:28

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 66, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["SubjID", "Difficulty_Rating", "AvgOffer_CFDWF234086Njpg", "AvgOffer_CFDBF049032Njpg", "AvgOffer_CFDBM010003Njpg", "AvgOffer_CFDWF212050Njpg", "AvgOffer_CFDWM209038Njpg", "AvgOffer_CFDBM019002Njpg", "AvgOffer_CFDBF041001Njpg", "AvgOffer_CFDWM024015Njpg", "TimePShare_CFDWF234086Njpg", "TimePShare_CFDBF049032Njpg", "TimePShare_CFDBM010003Njpg", "TimePShare_CFDWF212050Njpg", "TimePShare_CFDWM209038Njpg", "TimePShare_CFDBM019002Njpg", "TimePShare_CFDBF041001Njpg", "TimePShare_CFDWM024015Njpg", "PGoodBad_CFDWF234086Njpg", "PGoodBad_CFDBF049032Njpg", "PGoodBad_CFDBM010003Njpg", "PGoodBad_CFDWF212050Njpg", "PGoodBad_CFDWM209038Njpg", "PGoodBad_CFDBM019002Njpg", "PGoodBad_CFDBF041001Njpg", "PGoodBad_CFDWM024015Njpg", "WaytoShare_1Yes_2No", "Difficulty_Rating1", "AvgPOffer_CFDWF234086Njpg", "AvgPOffer_CFDBF049032Njpg", "AvgPOffer_CFDBM010003Njpg", "AvgPOffer_CFDWF212050Njpg", "AvgPOffer_CFDWM209038Njpg", "AvgPOffer_CFDBM019002Njpg", "AvgPOffer_CFDBF041001Njpg", "AvgPOffer_CFDWM024015Njpg", "TimesPShare_CFDWF234086Njpg", "TimesPShare_CFDBF049032Njpg", "TimesPShare_CFDBM010003Njpg", "TimesPShare_CFDWF212050Njpg", "TimesPShare_CFDWM209038Njpg", "TimesPShare_CFDBM019002Njpg", "TimesPShare_CFDBF041001Njpg", "TimesPShare_CFDWM024015Njpg", "PGoodBad_CFDWF234086Njpg1", "PGoodBad_CFDBF049032Njpg1", "PGoodBad_CFDBM010003Njpg1", "PGoodBad_CFDWF212050Njpg1", "PGoodBad_CFDWM209038Njpg1", "PGoodBad_CFDBM019002Njpg1", "PGoodBad_CFDBF041001Njpg1", "PGoodBad_CFDWM024015Njpg1", "WaytoShare_1Yes_2No1", "MorL_Incline_Offer", "How_Well_Strat", "MorL_Incline_Share", "How_Well_Strat1", "PartnerRace_Influence", "PartnerPA_Influence", "FrequencyofPShare_Influence", "PartnerGender_Influence", "PartnerRace_Influence1", "PartnerPA_Influence1", "PartnerOffer_Influence", "PreviousExperiences_Influence", "PartnerGender_Influence1"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
PTRPOSTQ1 = readtable(filename, opts);

end