function PTRPOSTQ = import_postq_file(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PTRPOSTQ = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  PTRPOSTQ = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  PTRPOSTQ = importfile("/Volumes/shlab/Projects/PTR/data/clean/POST_Q/PTR_POSTQ.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Jul-2022 20:04:51

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 49, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["SubjID", "Phase1_AvgOffer_CFDWF234086Njpg", "Phase1_AvgOffer_CFDBF049032Njpg", "Phase1_AvgOffer_CFDBM010003Njpg", "Phase1_AvgOffer_CFDWF212050Njpg", "Phase1_AvgOffer_CFDWM209038Njpg", "Phase1_AvgOffer_CFDBM019002Njpg", "Phase1_AvgOffer_CFDBF041001Njpg", "Phase1_AvgOffer_CFDWM024015Njpg", "Phase1_TimePShare_CFDWF234086Njpg", "Phase1_TimePShare_CFDBF049032Njpg", "Phase1_TimePShare_CFDBM010003Njpg", "Phase1_TimePShare_CFDWF212050Njpg", "Phase1_TimePShare_CFDWM209038Njpg", "Phase1_TimePShare_CFDBM019002Njpg", "Phase1_TimePShare_CFDBF041001Njpg", "Phase1_TimePShare_CFDWM024015Njpg", "Phase1_PGoodBad_CFDWF234086Njpg", "Phase1_PGoodBad_CFDBF049032Njpg", "Phase1_PGoodBad_CFDBM010003Njpg", "Phase1_PGoodBad_CFDWF212050Njpg", "Phase1_PGoodBad_CFDWM209038Njpg", "Phase1_PGoodBad_CFDBM019002Njpg", "Phase1_PGoodBad_CFDBF041001Njpg", "Phase1_PGoodBad_CFDWM024015Njpg", "Phase2_AvgPOffer_CFDWF234086Njpg", "Phase2_AvgPOffer_CFDBF049032Njpg", "Phase2_AvgPOffer_CFDBM010003Njpg", "Phase2_AvgPOffer_CFDWF212050Njpg", "Phase2_AvgPOffer_CFDWM209038Njpg", "Phase2_AvgPOffer_CFDBM019002Njpg", "Phase2_AvgPOffer_CFDBF041001Njpg", "Phase2_AvgPOffer_CFDWM024015Njpg", "Phase2_TimesPShare_CFDWF234086Njpg", "Phase2_TimesPShare_CFDBF049032Njpg", "Phase2_TimesPShare_CFDBM010003Njpg", "Phase2_TimesPShare_CFDWF212050Njpg", "Phase2_TimesPShare_CFDWM209038Njpg", "Phase2_TimesPShare_CFDBM019002Njpg", "Phase2_TimesPShare_CFDBF041001Njpg", "Phase2_TimesPShare_CFDWM024015Njpg", "Phase2_PGoodBad_CFDWF234086Njpg", "Phase2_PGoodBad_CFDBF049032Njpg", "Phase2_PGoodBad_CFDBM010003Njpg", "Phase2_PGoodBad_CFDWF212050Njpg", "Phase2_PGoodBad_CFDWM209038Njpg", "Phase2_PGoodBad_CFDBM019002Njpg", "Phase2_PGoodBad_CFDBF041001Njpg", "Phase2_PGoodBad_CFDWM024015Njpg"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
PTRPOSTQ = readtable(filename, opts);

end